FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", \
    "-Dquarkus.http.host=0.0.0.0", \
    "-Dquarkus.http.port=8080", \
    "-Dde.dopler.ms.login_server.services.external.TokenService/mp-rest/url=http://jwt-server:8080", \
    "-Dde.dopler.ms.login_server.services.external.CredentialsStoreService/mp-rest/url=http://credentials-store:8080" \
]
