FROM adoptopenjdk/openjdk11:ubi-minimal-jre
WORKDIR /work/
COPY target/lib /work/lib
COPY target/*-runner.jar /work/application.jar
RUN chmod 775 /work
EXPOSE 8080
CMD ["java", \
    "-Dquarkus.http.host=0.0.0.0", \
    "-Dquarkus.http.port=8080", \
    "-Dquarkus.datasource.jdbc.url=jdbc:h2:/data/ms-tokens;AUTO_SERVER=TRUE", \
    "-jar", \
    "./application.jar" \
]
